apiVersion: kubealex.com/v1
kind: K8SMediaserver
metadata:
  name: k8smediaserver-sample
spec:
  general:
    image_tag: latest
    ingress_host: k8s-mediaserver.k8s.test
    pgid: 1000
    plex_ingress_host: k8s-plex.k8s.test
    puid: 1000
    storage:
      nfs: false
      nfsPath: null
      nfsServer: null
      pvcName: mediaserver-pvc
      pvcStorageClass: {}
      size: 50Gi
  jackett:
    container:
      nodeSelector: {}
      port: 9117
    ingress:
      annotations: {}
      enabled: true
      path: /jackett
      tls:
        enabled: false
        secretName: ""
    service:
      extraLBService: false
      nodePort: null
      port: 9117
      type: ClusterIP
  plex:
    claim: CHANGEME
    container:
      nodeSelector: {}
      port: 32400
    ingress:
      annotations: {}
      enabled: true
      tls:
        enabled: false
        secretName: ""
    replicaCount: 1
    service:
      extraLBService: false
      nodePort: null
      port: 32400
      type: ClusterIP
  radarr:
    container:
      nodeSelector: {}
      port: 7878
    ingress:
      annotations: {}
      enabled: true
      path: /radarr
      tls:
        enabled: false
        secretName: ""
    service:
      extraLBService: false
      nodePort: null
      port: 7878
      type: ClusterIP
  sonarr:
    container:
      nodeSelector: {}
      port: 8989
    ingress:
      annotations: {}
      enabled: true
      path: /sonarr
      tls:
        enabled: false
        secretName: ""
    service:
      extraLBService: false
      nodePort: null
      port: 8989
      type: ClusterIP
  transmission:
    container:
      nodeSelector: {}
      port: 
        utp: 9091
        peer: 51413
    ingress:
      annotations: {}
      enabled: true
      path: /transmission
      tls:
        enabled: false
        secretName: ""
    service:
      utp:
        extraLBService: false
        nodePort: null
        port: 9091
        type: ClusterIP
      peer:
        extraLBService: false
        nodePort: null
        port: 51413
        type: ClusterIP
    config:
      auth: 
        enabled: false
        username: ""
        password: ""