---
{{ if .Values.service.http.extraLBService }}
### SERVICE
apiVersion: v1
kind: Service
metadata:
  name: sabnzbd-lb
  {{- with .Values.service.http.extraLBAnnotations }}
  annotations:
    {{- . | toYaml | nindent 4 }}
  {{- end }}
  labels:
    {{- include "sabnzbd.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.service.http.port }}
      targetPort: {{ .Values.container.port.http }}
      protocol: TCP
      name: sabnzbd-http
  selector:
    app: sabnzbd
{{ end }}
