apiVersion: kubealex.com/v1
kind: K8SMediaserver
metadata:
  name: k8smediaserver-sample
spec:
  # Default values copied from <project_dir>/helm-charts/k8s-mediaserver/values.yaml
  general: 
    ingress_host: k8s-test-loadbalancer.k8s.test
    plex_ingress_host: k8s-plex.k8s.test
    image_tag: latest
    puid: 1000
    pgid: 1000
    storage:
      pvcName: mediaserver-pvc
      size: 5Gi
      pvcStorageClass: []
      nfs: false 
      nfsServer: 
      nfsPath: 

  sonarr:
    container: 
      nodeSelector: {}
      port: 8989
    service:
      type: ClusterIP
      port: 8989
      nodePort: 
      extraLBService: false 

    ingress:
      enabled: true
      annotations: {}
      path: /sonarr
      tls:
        enabled: false
        secretName: ""

  radarr:
    container: 
      nodeSelector: {}
      port: 7878
    service:
      type: ClusterIP
      port: 7878
      nodePort: 
      extraLBService: false 

    ingress:
      enabled: true
      annotations: {}
      path: /radarr
      tls:
        enabled: false
        secretName: ""
    
  jackett:
    container: 
      nodeSelector: {}
      port: 9117
    service:
      type: ClusterIP
      port: 9117
      nodePort: 
      extraLBService: false 
    ingress:
      enabled: true
      annotations: {}
      path: /jackett
      tls:
        enabled: false
        secretName: ""
    
  transmission:
    container: 
      nodeSelector: {}
      port: 
        utp: 9091
        peer: 51413
    service:
      utp:
        type: ClusterIP
        port: 9091
        nodePort: 
        extraLBService: false
      peer:
        type: ClusterIP
        port: 51413
        nodePort:
        nodePortUDP: 
        extraLBService: false
    ingress:
      enabled: true
      annotations: {}
      path: /transmission
      tls:
        enabled: false
        secretName: ""
    config:
      auth: 
        enabled: false
        username: ""
        password: ""
        
  plex:
    claim: "CHANGEME"
    replicaCount: 1
    container: 
      nodeSelector: {}
      port: 32400
    service:
      type: ClusterIP
      port: 32400
      nodePort: 
      extraLBService: false 
    ingress:
      enabled: true
      annotations: {}
      tls:
        enabled: false
        secretName: ""