---
{{ if .Values.service.peer.extraLBService }}
### SERVICE
apiVersion: v1
kind: Service
metadata:
  name: transmission-lb-peer-udp
  {{- with .Values.service.peer.extraLBAnnotations }}
  annotations:
    {{- . | toYaml | nindent 4 }}
  {{- end }}
  labels:
    {{- include "transmission.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.service.peer.port }}
      targetPort: {{ .Values.container.port.peer }}
      protocol: UDP
      name: trans-peer-udp
  selector:
    app: transmission
{{ end }}

