{{ if .Values.seerr.enabled }}
---
### CONFIGMAP
apiVersion: v1
kind: ConfigMap
metadata:
  name: seerr-config
data:
  PGID: "{{ .Values.general.pgid }}"
  PUID: "{{ .Values.general.puid }}"
---
### DEPLOYMENT
apiVersion: apps/v1
kind: Deployment
metadata:
  name: seerr
  labels:
    {{- include "k8s-mediaserver.labels" . | nindent 4 }}
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      {{- include "k8s-mediaserver.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "k8s-mediaserver.selectorLabels" . | nindent 8 }}
        app: seerr
    spec:
      containers:
        - name: seerr
          envFrom:
            - configMapRef:
                name: seerr-config
          env:
            {{- with .Values.seerr.container.extraEnv }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          image: "{{ .Values.seerr.container.image }}:{{ .Values.seerr.container.tag }}"
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /api/v1/status
              port: {{ .Values.seerr.container.port }}
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 20
          livenessProbe:
            httpGet:
              path: /api/v1/status
              port: {{ .Values.seerr.container.port }}
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
          ports:
            - name: seerr-port
              containerPort: {{ .Values.seerr.container.port }}
              protocol: TCP
          volumeMounts:
          {{- if .Values.seerr.volume }}
            - name: {{ .Values.seerr.volume.name }}
              mountPath: /app/config
          {{- else }}
            - name: mediaserver-volume
              mountPath: "/app/config"
              subPath: "{{ .Values.general.storage.subPaths.config }}/seerr"
          {{- end }}
          {{- with .Values.seerr.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        {{- if not .Values.general.storage.customVolume }}
        - name: mediaserver-volume
          persistentVolumeClaim:
            claimName: {{ .Values.general.storage.pvcName }}
        {{- else }}
        - name: mediaserver-volume
          {{- toYaml .Values.general.storage.volumes | nindent 10 }}
        {{- end }}
        {{- if .Values.seerr.volume }}
        - name: {{ .Values.seerr.volume.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.seerr.volume.name }}
        {{- end }}
      {{- with merge .Values.seerr.container.nodeSelector .Values.general.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.general.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if eq .Values.general.podDistribution "cluster" }}
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/instance
                  operator: In
                  values:
                  - {{ .Release.Name }}
              topologyKey: "kubernetes.io/hostname"
            weight: 100
      {{- else if eq .Values.general.podDistribution "spread" }}
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: "kubernetes.io/hostname"
        whenUnsatisfiable: "ScheduleAnyway"
        labelSelector:
          matchLabels:
            app.kubernetes.io/instance: {{ .Release.Name }}
      {{- end }}
---
### SERVICES
apiVersion: v1
kind: Service
metadata:
  name: seerr
  labels:
    {{- include "k8s-mediaserver.labels" . | nindent 4 }}
spec:
  type: {{ .Values.seerr.service.type }}
  ports:
    - port: {{ .Values.seerr.service.port }}
      targetPort: {{ .Values.seerr.container.port }}
      protocol: TCP
{{ if eq .Values.seerr.service.type "NodePort" }}
      nodePort: {{ .Values.seerr.service.nodePort }}
{{ end }}
      name: seerr-port
  selector:
    app: seerr
---
{{ if .Values.seerr.service.extraLbService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: seerr-lb
  {{- with .Values.seerr.service.extraLbService.annotations }}
  annotations:
    {{- . | toYaml | nindent 4 }}
  {{- end }}
  labels:
    {{- include "k8s-mediaserver.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.seerr.service.extraLbService.port | default .Values.seerr.service.port }}
      targetPort: {{ .Values.seerr.container.port }}
      protocol: TCP
      name: seerr-port
  loadBalancerIP: {{ .Values.seerr.service.extraLbService.IP }}
  selector:
    app: seerr
{{ end }}
---
### INGRESS
{{ if .Values.seerr.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: seerr
  labels:
    {{- include "k8s-mediaserver.labels" . | nindent 4 }}
  {{- with .Values.seerr.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.seerr.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.general.ingress_host | quote }}
      secretName: {{ .Values.seerr.ingress.tls.secretName }}
{{ end }}
  ingressClassName: {{ .Values.general.ingress.ingressClassName }}
  rules:
    - host: {{ .Values.general.ingress_host | quote }}
      http:
        paths:
          - path: {{ .Values.seerr.ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: seerr
                port:
                  number: {{ .Values.seerr.service.port }}
{{ end }}
{{ end }}
