name: Lint and validate Helm chart
on:
  pull_request:
    types: [opened, reopened, edited, labeled]
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup helm 
        uses: azure/setup-helm@v3
        with:
           version: 'v3.10.0' 
        id: install-helm
       
      - name: Test helm
        run: helm template helm-charts/k8s-mediaserver
